Safety improvements
sakhmatd/swege pull request #11
Opened 2023-07-27 17:07 UTC by kovmir

Please accept my humble safety improvements to your `Makefile` and small polishes to `README.md`.

2023-07-27 18:09 UTC, sakhmatd requested changes
Please address the changes in the review, good to commit except for one line.

2023-07-27 18:09 UTC, sakhmatd commented on makefile
> +THREADS ?= false
This should not be set if absent, this is really experimental and currently full of bugs.

2023-07-27 18:51 UTC, sakhmatd approved these changes

2023-07-27 18:51 UTC, merged

2023-07-27 18:52 UTC, sakhmatd commented
Merged, thanks.

2023-07-28 05:55 UTC, kovmir commented
Can you please make a new release with these changes? `2.0.1` supposedly.

2023-07-28 12:45 UTC, sakhmatd commented
Done. There should also now be an automatic release triggered on every push to the master branch tagged "latest".