replace .ini with .csv config type
sakhmatd/swege pull request #4
Opened 2021-11-08 23:34 UTC by unInstance

INI parser is too much for such a small configuration file. Simple CSV file is just enough. If you merge this pull request and #3, then I will also update the man page.

I am glad to contribute to your project, hope you appreciate it.

2021-12-18 18:08 UTC, sakhmatd requested changes
Sorry it took me a while to look at this PR.

There are a number of issues with your approach.

1. The most simple one to address is the extension of the config file. Although .csv would reflect the format well, it would not reflect the intended use.
2. The attached .csv format does not reflect typical use of a csv format. It is good to think of a .csv as a table in a spreadsheet program, like LO Sheets or MS Excel (in fact, both are able to open CSV files and show them in such a way!).
3. The code used to separate the string is not very elegant. I would suggest using strtok() to tokenize the string. See C FAQ 13.6 for example usage.

To address 1, I would suggest using `.cfg` or similar for the config file extension.

2 is not necessarily bad, I would suggest a format like this instead:
```
title:My Website
source:src
destination:site
header:src/_header.html
footer:src/_footer.html
```

Again, this would not be a CSV in a traditional sense, but this is what I would like to see.

For 3, see how to use strtok/strtok_r. Make sure you can gracefully exit on empty fields and invalid configuration.

2021-12-20 12:55 UTC, unInstance commented
Please, review it again.

2022-04-19 13:00 UTC, sakhmatd commented
Sorry it took me a while to get to this PR.

The code as it is written right now is leaking memory, you strdup to allocate memory for strings in the config struct, but that memory never gets freed, unless the config is invalid. Check valgrind on the example project.

You should be able to free the memory at the end of the execution, just make sure this is caught in all instances. Alternatively, you could statically allocate, but this is less robust.

Once that is fixed, I think this is good enough to commit.

2022-04-19 17:35 UTC, sakhmatd approved these changes

2022-04-19 17:36 UTC, merged